HW13 WIP
tiburon-777/HW_OTUS pull request #14
Opened 2020-09-27 07:01 UTC by tiburon-777

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-10-02 16:56 UTC, kulti requested changes
По моему, решение движется в верном направлении. Надо закоммитить сгенерированный код и реализовать хэндлеры.

2020-10-02 16:56 UTC, kulti commented on hw12_13_14_15_calendar/grpc/google/api/annotations.proto
> +// Copyright (c) 2015, Google Inc.
Не понимаю, зачем эти гугловые файлы тут нужны.

2020-10-02 16:56 UTC, kulti commented on hw12_13_14_15_calendar/grpc/grpc.proto
> +syntax = "proto3";
Нет сгенеренного кода по этому файлу. Из-за этого ничего не собирается.

2020-10-07 13:20 UTC, tiburon-777 commented on hw12_13_14_15_calendar/grpc/google/api/annotations.proto
> +// Copyright (c) 2015, Google Inc.
Это чтоб grpc создал свои хэндлеры, если я правильно понял.

2020-10-07 13:21 UTC, tiburon-777 commented on hw12_13_14_15_calendar/grpc/grpc.proto
> +syntax = "proto3";
Да, совершенно верно. Не обратил внимание, что результирующие файлы не включены в коммит.

2020-10-10 12:47 UTC, kulti commented on hw12_13_14_15_calendar/grpc/google/api/annotations.proto
> +// Copyright (c) 2015, Google Inc.
Я понял, это для grpc-gateway. Он использует внутренние grpc прото-файлы, которые нельзя импортировать, как, например, empty.proto, нужно в репозиторий копировать.

2020-10-10 13:16 UTC, kulti requested changes
Нужно поправить запуск grpc-сервера и выбрать один подход к http-серверу. Также нужные юнит-тесты на API.

Остальное — косметика, повлияет только на баллы за "Понятность и чистота кода".

Если не будет юнит-тестов и код будет так себе, то получится всего 6 баллов — это незачет. У вас есть выбор, что именно сделать, чтобы набрать зачетные 7 баллов.

2020-10-10 13:16 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/handlers.go
> +type Service struct {
Этот Service еще нужно зарегестрировать в grpc-сервере.

2020-10-10 13:16 UTC, kulti commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	serverHTTP := internalhttp.NewServer(calendar, conf.Server.Address, conf.Server.Port)
Нужно выбрать один подход — либо свой http-сервер, либо grpc-gateway.

2020-10-10 13:16 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/converters.go
> +func pbevent2event(pbe *Event) (res event.Event, err error) {
Названия методов-конверторов непонятные и трудночитаемые. `pbEventToEvent` — читается намного легче, хотя все еще не очень понятно, что это.

Как вариант, можно сделать эти конверторы приватными методами у Service. Тогда у них сразу сузится область использования и видимости. Они относятся к работе с grpc запросами/ответами.

В месте вызова:
```
func (s Service) Create(ctx context.Context, event *Event) (*EventID, error) {
    storageEvent, err := s.buildStorageEvent(event)
    if err != nil {
    ...
}
```

2020-10-12 04:39 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/handlers.go
> +type Service struct {
Действительно, потерялась регистрация. Прописал.

2020-10-12 04:41 UTC, tiburon-777 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	serverHTTP := internalhttp.NewServer(calendar, conf.Server.Address, conf.Server.Port)
Удалил из генерации gateway

2020-10-12 06:39 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/handlers.go
> +		return nil, err
Исправил.

2020-10-12 06:39 UTC, tiburon-777 commented on hw12_13_14_15_calendar/grpcserver/grpcserver.proto
> +  rpc Create(Event) returns (EventID) {
Исправил

2020-10-12 07:15 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/converters.go
> +func pbevent2event(pbe *Event) (res event.Event, err error) {
Переписал.

2020-10-12 07:15 UTC, tiburon-777 commented
> Нужно поправить запуск grpc-сервера и выбрать один подход к http-серверу. Также нужные юнит-тесты на API.
> 
> Остальное — косметика, повлияет только на баллы за "Понятность и чистота кода".
> 
> Если не будет юнит-тестов и код будет так себе, то получится всего 6 баллов — это незачет. У вас есть выбор, что именно сделать, чтобы набрать зачетные 7 баллов.

Я хочу 10 :-)

2020-10-12 16:04 UTC, tiburon-777 commented
Тесты написал.

2020-10-12 17:59 UTC, kulti requested changes
Мне кажется, вы упустили один пункт задания:
> расширить "hello-world" сервер из ДЗ №12 до полноценного API;

Чтобы не писать http API вручную и предлагалось использовать grpc-gateway.

Сейчас разбалловка такая:
- Makefile заполнен и пайплайн зеленый - 1/1
- Реализовано GRPC API и make generate - 3/3
- Реализовано HTTP API - 0/2 балла
- Написаны юнит-тесты на API - 1/2
- Понятность и чистота кода - 1/2

Итого: 6 баллов. Если хотите 10-ку, то надо написать хорошие тесты и реализовать HTTP API.

2020-10-12 17:59 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/converters.go
> +	var events = []*Event{}
Тут можно преаллокацию сделать.

2020-10-12 17:59 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +func TestService(t *testing.T) {
Тесты должны тестировать сценарии. Сценарий — это отдельный аспект поведения приложения. Когда тесты короткие и тестируют что-то одно, с их помощью можно находить и исправлять баги, понимать, как работает система, их легко читать и дописывать.

При одном взгляде на текущий тест, не хочется разбираться, что там происходит, т.к. это полотно текста. В нем также есть один из признаков, что код плохой (любой код, не только тестов) — комментарии для разбиения на логические блоки.

2020-10-12 17:59 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +	require.Equal(t, &Event{ID: 1, Title: "Updated event", Date: cdate, Latency: ptypes.DurationProto(time.Hour * 48), Note: "Updated gen", UserID: 2222, NotifyTime: ptypes.DurationProto(time.Minute * 1
Из подобных проверок очень сложно понять, что проверяется.

Тесты — это тоже код, его тоже нужно проектировать и выделять сущности. Например, в подобном случае стоит выделить несколько слоев абстракции, чтобы тесты выглядели так (в примере используется testify/suite):
```
func (s *CalendarSuite) TestUpdateEvent() {
    oldEvent := s.generateEvent()
    s.createEvent(oldEvent)

    newEvent := s.generateEvent()
    s.updateEvent(oldEvent, newEvent)
    updatedEvent := s.getEventByDate(oldEvent.Date)

    s.Require.Equal(newEvent, updatedEvent)
}

...

func (s *CalendarSuite) createEvent(ev Event) {
    createdEvent, err := s.srv.Create(nil, s.eventToCreateRequest(ev))
    require.NoError(t, err, "can,t create event")
    require.NotEqual(t, createdEvent.ID, 0, `message ID may not be a "0"`)
}
```

2020-11-12 16:10 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +func TestService(t *testing.T) {
Разобрал простыню

2020-11-12 16:11 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +	require.Equal(t, &Event{ID: 1, Title: "Updated event", Date: cdate, Latency: ptypes.DurationProto(time.Hour * 48), Note: "Updated gen", UserID: 2222, NotifyTime: ptypes.DurationProto(time.Minute * 1
Использовал Suite.

2020-11-12 16:14 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/converters.go
> +	var events = []*Event{}
Сделал.

2020-11-14 10:07 UTC, kulti approved these changes
HTTP API появилось. Тесты стали в разы лучше. Над чистотой кода еще можно поработать, но думаю не стоит сейчас тратить время на это. Лучше учесть на будущее. ДЗ принято - 9/10.

2020-11-14 10:07 UTC, kulti commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +}
Тут может случится паника, если createdEvent будет пустой. Тогда все тесты завалятся. Лучше не падать в панику в тестах, чтобы она не прерывала выполнение все остальных тестов.

Также для лучшей читаемости рекомендую разбивать разбивать пустыми строчками логические блоки. Чаще всего, это три блока setup + action + assertion. Иногда action + assertion оставляют одним блоков, особенно, если в тесте несколько проверок. Например, в данном случае можно написать так:
```
func (s *TestSuite) TestCreateEvent() {
	controlEvent := testEvt1
	s.createEvent(&controlEvent)

	createdEvent := s.getEventByDate(controlEvent.Date)
	s.Require().Len(createdEvent, 1)
	s.Equal(&controlEvent, createdEvent[0])
}
```

2020-11-14 15:17 UTC, tiburon-777 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	signal.Notify(signals,syscall.SIGINT, syscall.SIGHUP)
Да. С SIGHUP я пожалуй погорячился.

2020-11-14 16:25 UTC, tiburon-777 commented on hw12_13_14_15_calendar/configs/config.toml
> +[Http]
Лишняя конечно. Это пережиток 12-го ДЗ

2020-11-14 16:26 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/config/config.go
> +	HTTP    Server
Убрал, вместе с hello-http сервером

2020-11-14 16:26 UTC, tiburon-777 commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	signal.Notify(signals,syscall.SIGINT, syscall.SIGHUP)
Исправил

2020-11-14 16:26 UTC, tiburon-777 commented on hw12_13_14_15_calendar/internal/grpcserver/handlers_test.go
> +}
Понял. Учту на будущее. Проверку длины добавил.

2020-11-14 16:34 UTC, tiburon-777 commented
Т.к. домашка принята, исправленную ветку солью сам

2020-11-14 16:34 UTC, merged